#!/bin/sh
#

if git diff --cached | grep --quiet "DONOTCOMMIT"
then
	echo ""
	grep -rn "DONOTCOMMIT" *
	echo "\n⚠️  Whoa buddy, looks like you almost commit something you weren't supposed to?"
	exit 1
fi
